services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment: # valable uniquement avec 1 BD - à update quand on fera 2 BD
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Morpyamdb
      MYSQL_USER: morpyam_appli
      MYSQL_PASSWORD: jR]0dNx8[F7pL2
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Volume persistant 

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data: